# Generated by Django 5.1.6 on 2025-03-03 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compatibility", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationrequest",
            name="requester",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
