# Generated by Django 5.1.6 on 2025-03-03 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compatibility", "0002_donationrequest_requester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationrequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
