# Generated by Django 5.1.6 on 2025-03-10 11:30

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compatibility", "0003_alter_donationrequest_requester"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="city",
            field=models.CharField(default="Unknown", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="donor",
            name="country",
            field=django_countries.fields.CountryField(default="Unknown", max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="donor",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="donationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
