# Generated by Django 5.1.6 on 2025-03-11 12:59

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compatibility", "0004_donor_city_donor_country_donor_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="donor",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="donor",
            name="location",
            field=models.CharField(
                blank=True, default="Unknown", max_length=255, null=True
            ),
        ),
    ]
