# Generated by Django 5.1.6 on 2025-03-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compatibility", "0005_alter_donor_city_alter_donor_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donor",
            name="state",
        ),
    ]
