# Generated by Django 5.1.6 on 2025-03-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compatibility", "0006_remove_donor_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
