# Generated by Django 5.1.6 on 2025-03-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compatibility", "0007_alter_donor_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="state_or_county",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
