# Generated by Django 5.1.6 on 2025-03-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compatibility", "0008_donor_state_or_county"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationrequest",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="donationrequest",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="donationrequest",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
